# Generated by Django 5.2.7 on 2025-12-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-views_count'], 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
